//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMarketConsumer.SuperMarketService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/SMServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Order[] OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Payment[] PaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Payment[] Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentsField, value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/SMServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Customer_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.OrderDetail[] OrderDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdateAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateAt {
            get {
                return this.CreateAtField;
            }
            set {
                if ((this.CreateAtField.Equals(value) != true)) {
                    this.CreateAtField = value;
                    this.RaisePropertyChanged("CreateAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Customer_ID {
            get {
                return this.Customer_IDField;
            }
            set {
                if ((this.Customer_IDField.Equals(value) != true)) {
                    this.Customer_IDField = value;
                    this.RaisePropertyChanged("Customer_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.OrderDetail[] OrderDetails {
            get {
                return this.OrderDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDetailsField, value) != true)) {
                    this.OrderDetailsField = value;
                    this.RaisePropertyChanged("OrderDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderName {
            get {
                return this.OrderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNameField, value) != true)) {
                    this.OrderNameField = value;
                    this.RaisePropertyChanged("OrderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateAt {
            get {
                return this.UpdateAtField;
            }
            set {
                if ((this.UpdateAtField.Equals(value) != true)) {
                    this.UpdateAtField = value;
                    this.RaisePropertyChanged("UpdateAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/SMServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Payment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Customer_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PaymentDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Customer_ID {
            get {
                return this.Customer_IDField;
            }
            set {
                if ((this.Customer_IDField.Equals(value) != true)) {
                    this.Customer_IDField = value;
                    this.RaisePropertyChanged("Customer_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetail", Namespace="http://schemas.datacontract.org/2004/07/SMServiceApplication")]
    [System.SerializableAttribute()]
    public partial class OrderDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Order OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Order_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Product ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Product_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Order Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order_ID {
            get {
                return this.Order_IDField;
            }
            set {
                if ((this.Order_IDField.Equals(value) != true)) {
                    this.Order_IDField = value;
                    this.RaisePropertyChanged("Order_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Product_ID {
            get {
                return this.Product_IDField;
            }
            set {
                if ((this.Product_IDField.Equals(value) != true)) {
                    this.Product_IDField = value;
                    this.RaisePropertyChanged("Product_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/SMServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Category_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.OrderDetail[] OrderDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Provider ProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Provider_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Category_ID {
            get {
                return this.Category_IDField;
            }
            set {
                if ((this.Category_IDField.Equals(value) != true)) {
                    this.Category_IDField = value;
                    this.RaisePropertyChanged("Category_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.OrderDetail[] OrderDetails {
            get {
                return this.OrderDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDetailsField, value) != true)) {
                    this.OrderDetailsField = value;
                    this.RaisePropertyChanged("OrderDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Provider Provider {
            get {
                return this.ProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderField, value) != true)) {
                    this.ProviderField = value;
                    this.RaisePropertyChanged("Provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Provider_ID {
            get {
                return this.Provider_IDField;
            }
            set {
                if ((this.Provider_IDField.Equals(value) != true)) {
                    this.Provider_IDField = value;
                    this.RaisePropertyChanged("Provider_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityField, value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/SMServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provider", Namespace="http://schemas.datacontract.org/2004/07/SMServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Provider : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/SMServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Role RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Role_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Role_ID {
            get {
                return this.Role_IDField;
            }
            set {
                if ((this.Role_IDField.Equals(value) != true)) {
                    this.Role_IDField = value;
                    this.RaisePropertyChanged("Role_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/SMServiceApplication")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SuperMarketConsumer.SuperMarketService.Employee[] EmployeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SuperMarketConsumer.SuperMarketService.Employee[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SuperMarketService.ISuperMarketService")]
    public interface ISuperMarketService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetCustomers", ReplyAction="http://tempuri.org/ISuperMarketService/GetCustomersResponse")]
        SuperMarketConsumer.SuperMarketService.Customer[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetCustomers", ReplyAction="http://tempuri.org/ISuperMarketService/GetCustomersResponse")]
        System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Customer[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddCustomer", ReplyAction="http://tempuri.org/ISuperMarketService/AddCustomerResponse")]
        bool AddCustomer(SuperMarketConsumer.SuperMarketService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddCustomer", ReplyAction="http://tempuri.org/ISuperMarketService/AddCustomerResponse")]
        System.Threading.Tasks.Task<bool> AddCustomerAsync(SuperMarketConsumer.SuperMarketService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditCustomer", ReplyAction="http://tempuri.org/ISuperMarketService/EditCustomerResponse")]
        bool EditCustomer(string id, SuperMarketConsumer.SuperMarketService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditCustomer", ReplyAction="http://tempuri.org/ISuperMarketService/EditCustomerResponse")]
        System.Threading.Tasks.Task<bool> EditCustomerAsync(string id, SuperMarketConsumer.SuperMarketService.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteCustomer", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteCustomerResponse")]
        bool DeleteCustomer(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteCustomer", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteCustomerResponse")]
        System.Threading.Tasks.Task<bool> DeleteCustomerAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetCategories", ReplyAction="http://tempuri.org/ISuperMarketService/GetCategoriesResponse")]
        SuperMarketConsumer.SuperMarketService.Category[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetCategories", ReplyAction="http://tempuri.org/ISuperMarketService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Category[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddCategory", ReplyAction="http://tempuri.org/ISuperMarketService/AddCategoryResponse")]
        bool AddCategory(SuperMarketConsumer.SuperMarketService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddCategory", ReplyAction="http://tempuri.org/ISuperMarketService/AddCategoryResponse")]
        System.Threading.Tasks.Task<bool> AddCategoryAsync(SuperMarketConsumer.SuperMarketService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditCategory", ReplyAction="http://tempuri.org/ISuperMarketService/EditCategoryResponse")]
        bool EditCategory(string id, SuperMarketConsumer.SuperMarketService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditCategory", ReplyAction="http://tempuri.org/ISuperMarketService/EditCategoryResponse")]
        System.Threading.Tasks.Task<bool> EditCategoryAsync(string id, SuperMarketConsumer.SuperMarketService.Category category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteCategory", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteCategoryResponse")]
        bool DeleteCategory(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteCategory", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteCategoryResponse")]
        System.Threading.Tasks.Task<bool> DeleteCategoryAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetProducts", ReplyAction="http://tempuri.org/ISuperMarketService/GetProductsResponse")]
        SuperMarketConsumer.SuperMarketService.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetProducts", ReplyAction="http://tempuri.org/ISuperMarketService/GetProductsResponse")]
        System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddProduct", ReplyAction="http://tempuri.org/ISuperMarketService/AddProductResponse")]
        bool AddProduct(SuperMarketConsumer.SuperMarketService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddProduct", ReplyAction="http://tempuri.org/ISuperMarketService/AddProductResponse")]
        System.Threading.Tasks.Task<bool> AddProductAsync(SuperMarketConsumer.SuperMarketService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditProduct", ReplyAction="http://tempuri.org/ISuperMarketService/EditProductResponse")]
        bool EditProduct(string id, SuperMarketConsumer.SuperMarketService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditProduct", ReplyAction="http://tempuri.org/ISuperMarketService/EditProductResponse")]
        System.Threading.Tasks.Task<bool> EditProductAsync(string id, SuperMarketConsumer.SuperMarketService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteProduct", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteProductResponse")]
        bool DeleteProduct(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteProduct", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteProductResponse")]
        System.Threading.Tasks.Task<bool> DeleteProductAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetOrders", ReplyAction="http://tempuri.org/ISuperMarketService/GetOrdersResponse")]
        SuperMarketConsumer.SuperMarketService.Order[] GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetOrders", ReplyAction="http://tempuri.org/ISuperMarketService/GetOrdersResponse")]
        System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Order[]> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddOrder", ReplyAction="http://tempuri.org/ISuperMarketService/AddOrderResponse")]
        bool AddOrder(SuperMarketConsumer.SuperMarketService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddOrder", ReplyAction="http://tempuri.org/ISuperMarketService/AddOrderResponse")]
        System.Threading.Tasks.Task<bool> AddOrderAsync(SuperMarketConsumer.SuperMarketService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditOrder", ReplyAction="http://tempuri.org/ISuperMarketService/EditOrderResponse")]
        bool EditOrder(string id, SuperMarketConsumer.SuperMarketService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditOrder", ReplyAction="http://tempuri.org/ISuperMarketService/EditOrderResponse")]
        System.Threading.Tasks.Task<bool> EditOrderAsync(string id, SuperMarketConsumer.SuperMarketService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteOrder", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteOrderResponse")]
        bool DeleteOrder(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteOrder", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteOrderResponse")]
        System.Threading.Tasks.Task<bool> DeleteOrderAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetOrderDetails", ReplyAction="http://tempuri.org/ISuperMarketService/GetOrderDetailsResponse")]
        SuperMarketConsumer.SuperMarketService.OrderDetail[] GetOrderDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetOrderDetails", ReplyAction="http://tempuri.org/ISuperMarketService/GetOrderDetailsResponse")]
        System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.OrderDetail[]> GetOrderDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddOrderDetail", ReplyAction="http://tempuri.org/ISuperMarketService/AddOrderDetailResponse")]
        bool AddOrderDetail(SuperMarketConsumer.SuperMarketService.OrderDetail orderDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddOrderDetail", ReplyAction="http://tempuri.org/ISuperMarketService/AddOrderDetailResponse")]
        System.Threading.Tasks.Task<bool> AddOrderDetailAsync(SuperMarketConsumer.SuperMarketService.OrderDetail orderDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditOrderDetail", ReplyAction="http://tempuri.org/ISuperMarketService/EditOrderDetailResponse")]
        bool EditOrderDetail(string id, SuperMarketConsumer.SuperMarketService.OrderDetail orderDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditOrderDetail", ReplyAction="http://tempuri.org/ISuperMarketService/EditOrderDetailResponse")]
        System.Threading.Tasks.Task<bool> EditOrderDetailAsync(string id, SuperMarketConsumer.SuperMarketService.OrderDetail orderDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteOrderDetail", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteOrderDetailResponse")]
        bool DeleteOrderDetail(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteOrderDetail", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteOrderDetailResponse")]
        System.Threading.Tasks.Task<bool> DeleteOrderDetailAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetPayments", ReplyAction="http://tempuri.org/ISuperMarketService/GetPaymentsResponse")]
        SuperMarketConsumer.SuperMarketService.Payment[] GetPayments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetPayments", ReplyAction="http://tempuri.org/ISuperMarketService/GetPaymentsResponse")]
        System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Payment[]> GetPaymentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddPayment", ReplyAction="http://tempuri.org/ISuperMarketService/AddPaymentResponse")]
        bool AddPayment(SuperMarketConsumer.SuperMarketService.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddPayment", ReplyAction="http://tempuri.org/ISuperMarketService/AddPaymentResponse")]
        System.Threading.Tasks.Task<bool> AddPaymentAsync(SuperMarketConsumer.SuperMarketService.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditPayment", ReplyAction="http://tempuri.org/ISuperMarketService/EditPaymentResponse")]
        bool EditPayment(string id, SuperMarketConsumer.SuperMarketService.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditPayment", ReplyAction="http://tempuri.org/ISuperMarketService/EditPaymentResponse")]
        System.Threading.Tasks.Task<bool> EditPaymentAsync(string id, SuperMarketConsumer.SuperMarketService.Payment payment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeletePayment", ReplyAction="http://tempuri.org/ISuperMarketService/DeletePaymentResponse")]
        bool DeletePayment(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeletePayment", ReplyAction="http://tempuri.org/ISuperMarketService/DeletePaymentResponse")]
        System.Threading.Tasks.Task<bool> DeletePaymentAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetEmployees", ReplyAction="http://tempuri.org/ISuperMarketService/GetEmployeesResponse")]
        SuperMarketConsumer.SuperMarketService.Employee[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetEmployees", ReplyAction="http://tempuri.org/ISuperMarketService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Employee[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddEmployee", ReplyAction="http://tempuri.org/ISuperMarketService/AddEmployeeResponse")]
        bool AddEmployee(SuperMarketConsumer.SuperMarketService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddEmployee", ReplyAction="http://tempuri.org/ISuperMarketService/AddEmployeeResponse")]
        System.Threading.Tasks.Task<bool> AddEmployeeAsync(SuperMarketConsumer.SuperMarketService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditEmployee", ReplyAction="http://tempuri.org/ISuperMarketService/EditEmployeeResponse")]
        bool EditEmployee(string id, SuperMarketConsumer.SuperMarketService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditEmployee", ReplyAction="http://tempuri.org/ISuperMarketService/EditEmployeeResponse")]
        System.Threading.Tasks.Task<bool> EditEmployeeAsync(string id, SuperMarketConsumer.SuperMarketService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteEmployee", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteEmployeeResponse")]
        bool DeleteEmployee(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteEmployee", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetRoles", ReplyAction="http://tempuri.org/ISuperMarketService/GetRolesResponse")]
        SuperMarketConsumer.SuperMarketService.Role[] GetRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetRoles", ReplyAction="http://tempuri.org/ISuperMarketService/GetRolesResponse")]
        System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Role[]> GetRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddRole", ReplyAction="http://tempuri.org/ISuperMarketService/AddRoleResponse")]
        bool AddRole(SuperMarketConsumer.SuperMarketService.Role role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddRole", ReplyAction="http://tempuri.org/ISuperMarketService/AddRoleResponse")]
        System.Threading.Tasks.Task<bool> AddRoleAsync(SuperMarketConsumer.SuperMarketService.Role role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditRole", ReplyAction="http://tempuri.org/ISuperMarketService/EditRoleResponse")]
        bool EditRole(string id, SuperMarketConsumer.SuperMarketService.Role Role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditRole", ReplyAction="http://tempuri.org/ISuperMarketService/EditRoleResponse")]
        System.Threading.Tasks.Task<bool> EditRoleAsync(string id, SuperMarketConsumer.SuperMarketService.Role Role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteRole", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteRoleResponse")]
        bool DeleteRole(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteRole", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteRoleResponse")]
        System.Threading.Tasks.Task<bool> DeleteRoleAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetProviders", ReplyAction="http://tempuri.org/ISuperMarketService/GetProvidersResponse")]
        SuperMarketConsumer.SuperMarketService.Provider[] GetProviders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/GetProviders", ReplyAction="http://tempuri.org/ISuperMarketService/GetProvidersResponse")]
        System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Provider[]> GetProvidersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddProvider", ReplyAction="http://tempuri.org/ISuperMarketService/AddProviderResponse")]
        bool AddProvider(SuperMarketConsumer.SuperMarketService.Provider provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/AddProvider", ReplyAction="http://tempuri.org/ISuperMarketService/AddProviderResponse")]
        System.Threading.Tasks.Task<bool> AddProviderAsync(SuperMarketConsumer.SuperMarketService.Provider provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditProvider", ReplyAction="http://tempuri.org/ISuperMarketService/EditProviderResponse")]
        bool EditProvider(string id, SuperMarketConsumer.SuperMarketService.Provider provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/EditProvider", ReplyAction="http://tempuri.org/ISuperMarketService/EditProviderResponse")]
        System.Threading.Tasks.Task<bool> EditProviderAsync(string id, SuperMarketConsumer.SuperMarketService.Provider provider);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteProvider", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteProviderResponse")]
        bool DeleteProvider(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISuperMarketService/DeleteProvider", ReplyAction="http://tempuri.org/ISuperMarketService/DeleteProviderResponse")]
        System.Threading.Tasks.Task<bool> DeleteProviderAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISuperMarketServiceChannel : SuperMarketConsumer.SuperMarketService.ISuperMarketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuperMarketServiceClient : System.ServiceModel.ClientBase<SuperMarketConsumer.SuperMarketService.ISuperMarketService>, SuperMarketConsumer.SuperMarketService.ISuperMarketService {
        
        public SuperMarketServiceClient() {
        }
        
        public SuperMarketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuperMarketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperMarketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuperMarketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SuperMarketConsumer.SuperMarketService.Customer[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Customer[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public bool AddCustomer(SuperMarketConsumer.SuperMarketService.Customer customer) {
            return base.Channel.AddCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<bool> AddCustomerAsync(SuperMarketConsumer.SuperMarketService.Customer customer) {
            return base.Channel.AddCustomerAsync(customer);
        }
        
        public bool EditCustomer(string id, SuperMarketConsumer.SuperMarketService.Customer customer) {
            return base.Channel.EditCustomer(id, customer);
        }
        
        public System.Threading.Tasks.Task<bool> EditCustomerAsync(string id, SuperMarketConsumer.SuperMarketService.Customer customer) {
            return base.Channel.EditCustomerAsync(id, customer);
        }
        
        public bool DeleteCustomer(string id) {
            return base.Channel.DeleteCustomer(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCustomerAsync(string id) {
            return base.Channel.DeleteCustomerAsync(id);
        }
        
        public SuperMarketConsumer.SuperMarketService.Category[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Category[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public bool AddCategory(SuperMarketConsumer.SuperMarketService.Category category) {
            return base.Channel.AddCategory(category);
        }
        
        public System.Threading.Tasks.Task<bool> AddCategoryAsync(SuperMarketConsumer.SuperMarketService.Category category) {
            return base.Channel.AddCategoryAsync(category);
        }
        
        public bool EditCategory(string id, SuperMarketConsumer.SuperMarketService.Category category) {
            return base.Channel.EditCategory(id, category);
        }
        
        public System.Threading.Tasks.Task<bool> EditCategoryAsync(string id, SuperMarketConsumer.SuperMarketService.Category category) {
            return base.Channel.EditCategoryAsync(id, category);
        }
        
        public bool DeleteCategory(string id) {
            return base.Channel.DeleteCategory(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(string id) {
            return base.Channel.DeleteCategoryAsync(id);
        }
        
        public SuperMarketConsumer.SuperMarketService.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public bool AddProduct(SuperMarketConsumer.SuperMarketService.Product product) {
            return base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task<bool> AddProductAsync(SuperMarketConsumer.SuperMarketService.Product product) {
            return base.Channel.AddProductAsync(product);
        }
        
        public bool EditProduct(string id, SuperMarketConsumer.SuperMarketService.Product product) {
            return base.Channel.EditProduct(id, product);
        }
        
        public System.Threading.Tasks.Task<bool> EditProductAsync(string id, SuperMarketConsumer.SuperMarketService.Product product) {
            return base.Channel.EditProductAsync(id, product);
        }
        
        public bool DeleteProduct(string id) {
            return base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProductAsync(string id) {
            return base.Channel.DeleteProductAsync(id);
        }
        
        public SuperMarketConsumer.SuperMarketService.Order[] GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Order[]> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public bool AddOrder(SuperMarketConsumer.SuperMarketService.Order order) {
            return base.Channel.AddOrder(order);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrderAsync(SuperMarketConsumer.SuperMarketService.Order order) {
            return base.Channel.AddOrderAsync(order);
        }
        
        public bool EditOrder(string id, SuperMarketConsumer.SuperMarketService.Order order) {
            return base.Channel.EditOrder(id, order);
        }
        
        public System.Threading.Tasks.Task<bool> EditOrderAsync(string id, SuperMarketConsumer.SuperMarketService.Order order) {
            return base.Channel.EditOrderAsync(id, order);
        }
        
        public bool DeleteOrder(string id) {
            return base.Channel.DeleteOrder(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteOrderAsync(string id) {
            return base.Channel.DeleteOrderAsync(id);
        }
        
        public SuperMarketConsumer.SuperMarketService.OrderDetail[] GetOrderDetails() {
            return base.Channel.GetOrderDetails();
        }
        
        public System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.OrderDetail[]> GetOrderDetailsAsync() {
            return base.Channel.GetOrderDetailsAsync();
        }
        
        public bool AddOrderDetail(SuperMarketConsumer.SuperMarketService.OrderDetail orderDetail) {
            return base.Channel.AddOrderDetail(orderDetail);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrderDetailAsync(SuperMarketConsumer.SuperMarketService.OrderDetail orderDetail) {
            return base.Channel.AddOrderDetailAsync(orderDetail);
        }
        
        public bool EditOrderDetail(string id, SuperMarketConsumer.SuperMarketService.OrderDetail orderDetail) {
            return base.Channel.EditOrderDetail(id, orderDetail);
        }
        
        public System.Threading.Tasks.Task<bool> EditOrderDetailAsync(string id, SuperMarketConsumer.SuperMarketService.OrderDetail orderDetail) {
            return base.Channel.EditOrderDetailAsync(id, orderDetail);
        }
        
        public bool DeleteOrderDetail(string id) {
            return base.Channel.DeleteOrderDetail(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteOrderDetailAsync(string id) {
            return base.Channel.DeleteOrderDetailAsync(id);
        }
        
        public SuperMarketConsumer.SuperMarketService.Payment[] GetPayments() {
            return base.Channel.GetPayments();
        }
        
        public System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Payment[]> GetPaymentsAsync() {
            return base.Channel.GetPaymentsAsync();
        }
        
        public bool AddPayment(SuperMarketConsumer.SuperMarketService.Payment payment) {
            return base.Channel.AddPayment(payment);
        }
        
        public System.Threading.Tasks.Task<bool> AddPaymentAsync(SuperMarketConsumer.SuperMarketService.Payment payment) {
            return base.Channel.AddPaymentAsync(payment);
        }
        
        public bool EditPayment(string id, SuperMarketConsumer.SuperMarketService.Payment payment) {
            return base.Channel.EditPayment(id, payment);
        }
        
        public System.Threading.Tasks.Task<bool> EditPaymentAsync(string id, SuperMarketConsumer.SuperMarketService.Payment payment) {
            return base.Channel.EditPaymentAsync(id, payment);
        }
        
        public bool DeletePayment(string id) {
            return base.Channel.DeletePayment(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePaymentAsync(string id) {
            return base.Channel.DeletePaymentAsync(id);
        }
        
        public SuperMarketConsumer.SuperMarketService.Employee[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Employee[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public bool AddEmployee(SuperMarketConsumer.SuperMarketService.Employee employee) {
            return base.Channel.AddEmployee(employee);
        }
        
        public System.Threading.Tasks.Task<bool> AddEmployeeAsync(SuperMarketConsumer.SuperMarketService.Employee employee) {
            return base.Channel.AddEmployeeAsync(employee);
        }
        
        public bool EditEmployee(string id, SuperMarketConsumer.SuperMarketService.Employee employee) {
            return base.Channel.EditEmployee(id, employee);
        }
        
        public System.Threading.Tasks.Task<bool> EditEmployeeAsync(string id, SuperMarketConsumer.SuperMarketService.Employee employee) {
            return base.Channel.EditEmployeeAsync(id, employee);
        }
        
        public bool DeleteEmployee(string id) {
            return base.Channel.DeleteEmployee(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(string id) {
            return base.Channel.DeleteEmployeeAsync(id);
        }
        
        public SuperMarketConsumer.SuperMarketService.Role[] GetRoles() {
            return base.Channel.GetRoles();
        }
        
        public System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Role[]> GetRolesAsync() {
            return base.Channel.GetRolesAsync();
        }
        
        public bool AddRole(SuperMarketConsumer.SuperMarketService.Role role) {
            return base.Channel.AddRole(role);
        }
        
        public System.Threading.Tasks.Task<bool> AddRoleAsync(SuperMarketConsumer.SuperMarketService.Role role) {
            return base.Channel.AddRoleAsync(role);
        }
        
        public bool EditRole(string id, SuperMarketConsumer.SuperMarketService.Role Role) {
            return base.Channel.EditRole(id, Role);
        }
        
        public System.Threading.Tasks.Task<bool> EditRoleAsync(string id, SuperMarketConsumer.SuperMarketService.Role Role) {
            return base.Channel.EditRoleAsync(id, Role);
        }
        
        public bool DeleteRole(string id) {
            return base.Channel.DeleteRole(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteRoleAsync(string id) {
            return base.Channel.DeleteRoleAsync(id);
        }
        
        public SuperMarketConsumer.SuperMarketService.Provider[] GetProviders() {
            return base.Channel.GetProviders();
        }
        
        public System.Threading.Tasks.Task<SuperMarketConsumer.SuperMarketService.Provider[]> GetProvidersAsync() {
            return base.Channel.GetProvidersAsync();
        }
        
        public bool AddProvider(SuperMarketConsumer.SuperMarketService.Provider provider) {
            return base.Channel.AddProvider(provider);
        }
        
        public System.Threading.Tasks.Task<bool> AddProviderAsync(SuperMarketConsumer.SuperMarketService.Provider provider) {
            return base.Channel.AddProviderAsync(provider);
        }
        
        public bool EditProvider(string id, SuperMarketConsumer.SuperMarketService.Provider provider) {
            return base.Channel.EditProvider(id, provider);
        }
        
        public System.Threading.Tasks.Task<bool> EditProviderAsync(string id, SuperMarketConsumer.SuperMarketService.Provider provider) {
            return base.Channel.EditProviderAsync(id, provider);
        }
        
        public bool DeleteProvider(string id) {
            return base.Channel.DeleteProvider(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteProviderAsync(string id) {
            return base.Channel.DeleteProviderAsync(id);
        }
    }
}
